# Site settings
title: Dozer Zone
name: Dozer Zone
email: mail@dozer.cc
description: 'Dozer&#039;s Technology Blog'
keywords: 'Dozer,dozer,blog,java,互联网,翔工作室,大众点评'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dozer.cc" # the base hostname & protocol for your site
github: dozer47528
twitter: dozer47528

author:
  name: Dozer
  email: mail@dozer.cc
  github: dozer47528
  twitter: dozer47528
  bio: 'Dozer&#039;s Technology Blog'
  email_md5: 3cccd2b313d9e9e1019f7a6784a6a084


# Build settings
paginate: 20
paginate_path: "page/:num/"
highlighter: pygments
markdown: kramdown
rss_path: feed
categories_path: categories.html
tags_path: tags.html
